export const OWNER_LIST_COLUMNS = [
  'name',
  'surname',
  'place_of_birth',
  'birth_date',
  'province',
  'residence',
  'address',
  'id_card_number',
  'id_card_issue_date',
  'id_card_expiration_date',
  'tax_code',
  'phone_number',
  'email',
  'documents',
] as const;

export const OWNER_LIST_LABELS: Record<string, string> = {
  name: 'Nome',
  surname: 'Cognome',
  place_of_birth: 'Luogo di nascita',
  birth_date: 'Data di nascita',
  province: 'Prov.',
  residence: 'Residenza',
  address: 'Indirizzo',
  id_card_number: 'N° carta identità',
  id_card_issue_date: 'Rilascio carta',
  id_card_expiration_date: 'Scadenza carta',
  tax_code: 'Codice fiscale',
  phone_number: 'Telefono',
  email: 'Email',
  documents: 'Documenti',
};
