export const STAY_LIST_COLUMNS = [
  'owner',
  'dogs',
  'area',
  'box',
  'is_picked_up',
  'arrival_date',
  'departure_date',
  'notes',
  'boarding_fee',
  'deposit',
  'outstanding_balance',
  'total_due',
  'payment_type',
] as const;

export const STAY_LIST_LABELS: Record<string, string> = {
  owner: 'Proprietario',
  dogs: 'Cani',
  area: 'Area',
  box: 'Box',
  arrival_date: 'Arrivo',
  departure_date: 'Uscita',
  is_picked_up: 'Ritirato',
  notes: 'Note',
  boarding_fee: 'Retta',
  deposit: 'Acconto',
  outstanding_balance: 'Saldo residuo',
  total_due: 'Totale da pagare',
  payment_type: 'Pagamento',
};
